/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as DevDashboardRouteImport } from './routes/dev/dashboard'
import { Route as DevNoAccessRouteImport } from './routes/dev/no-access'
import { Route as DevUiRouteImport } from './routes/dev/ui'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminBookingsRouteImport } from './routes/_app/admin/bookings'
import { Route as AppAdminCalendarRouteImport } from './routes/_app/admin/calendar'
import { Route as AppAdminExpensesRouteImport } from './routes/_app/admin/expenses'
import { Route as AppAdminPlansRouteImport } from './routes/_app/admin/plans'
import { Route as AppAdminTeamRouteImport } from './routes/_app/admin/team'
import { Route as AppPropertiesIndexRouteImport } from './routes/_app/properties/index'
import { Route as AppPropertiesPropertyIdRouteImport } from './routes/_app/properties/$propertyId'
import { Route as AppAdminPropertiesIndexRouteImport } from './routes/_app/admin/properties/index'
import { Route as AppAdminPropertiesPropertyIdRouteImport } from './routes/_app/admin/properties/$propertyId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const DevDashboardRoute = DevDashboardRouteImport.update({
  id: '/dev/dashboard',
  path: '/dev/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DevNoAccessRoute = DevNoAccessRouteImport.update({
  id: '/dev/no-access',
  path: '/dev/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: '/dev/ui',
  path: '/dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBookingsRoute = AppAdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCalendarRoute = AppAdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminExpensesRoute = AppAdminExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPlansRoute = AppAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTeamRoute = AppAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppPropertiesIndexRoute = AppPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesPropertyIdRoute = AppPropertiesPropertyIdRouteImport.update({
  id: '/properties/$propertyId',
  path: '/properties/$propertyId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPropertiesIndexRoute = AppAdminPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPropertiesPropertyIdRoute =
  AppAdminPropertiesPropertyIdRouteImport.update({
    id: '/properties/$propertyId',
    path: '/properties/$propertyId',
    getParentRoute: () => AppAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/account': typeof AppAccountRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dev/dashboard': typeof DevDashboardRoute
  '/dev/no-access': typeof DevNoAccessRoute
  '/dev/ui': typeof DevUiRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/bookings': typeof AppAdminBookingsRoute
  '/admin/calendar': typeof AppAdminCalendarRoute
  '/admin/expenses': typeof AppAdminExpensesRoute
  '/admin/plans': typeof AppAdminPlansRoute
  '/admin/team': typeof AppAdminTeamRoute
  '/properties/$propertyId': typeof AppPropertiesPropertyIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/properties/': typeof AppPropertiesIndexRoute
  '/admin/properties/$propertyId': typeof AppAdminPropertiesPropertyIdRoute
  '/admin/properties/': typeof AppAdminPropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/sso-callback': typeof SsoCallbackRoute
  '/account': typeof AppAccountRoute
  '/dev/dashboard': typeof DevDashboardRoute
  '/dev/no-access': typeof DevNoAccessRoute
  '/dev/ui': typeof DevUiRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/': typeof AppIndexRoute
  '/admin/bookings': typeof AppAdminBookingsRoute
  '/admin/calendar': typeof AppAdminCalendarRoute
  '/admin/expenses': typeof AppAdminExpensesRoute
  '/admin/plans': typeof AppAdminPlansRoute
  '/admin/team': typeof AppAdminTeamRoute
  '/properties/$propertyId': typeof AppPropertiesPropertyIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/properties': typeof AppPropertiesIndexRoute
  '/admin/properties/$propertyId': typeof AppAdminPropertiesPropertyIdRoute
  '/admin/properties': typeof AppAdminPropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sso-callback': typeof SsoCallbackRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/dev/dashboard': typeof DevDashboardRoute
  '/dev/no-access': typeof DevNoAccessRoute
  '/dev/ui': typeof DevUiRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/bookings': typeof AppAdminBookingsRoute
  '/_app/admin/calendar': typeof AppAdminCalendarRoute
  '/_app/admin/expenses': typeof AppAdminExpensesRoute
  '/_app/admin/plans': typeof AppAdminPlansRoute
  '/_app/admin/team': typeof AppAdminTeamRoute
  '/_app/properties/$propertyId': typeof AppPropertiesPropertyIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/properties/': typeof AppPropertiesIndexRoute
  '/_app/admin/properties/$propertyId': typeof AppAdminPropertiesPropertyIdRoute
  '/_app/admin/properties/': typeof AppAdminPropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sso-callback'
    | '/account'
    | '/admin'
    | '/dev/dashboard'
    | '/dev/no-access'
    | '/dev/ui'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/expenses'
    | '/admin/plans'
    | '/admin/team'
    | '/properties/$propertyId'
    | '/admin/'
    | '/properties/'
    | '/admin/properties/$propertyId'
    | '/admin/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sso-callback'
    | '/account'
    | '/dev/dashboard'
    | '/dev/no-access'
    | '/dev/ui'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/expenses'
    | '/admin/plans'
    | '/admin/team'
    | '/properties/$propertyId'
    | '/admin'
    | '/properties'
    | '/admin/properties/$propertyId'
    | '/admin/properties'
  id:
    | '__root__'
    | '/_app'
    | '/sso-callback'
    | '/_app/account'
    | '/_app/admin'
    | '/dev/dashboard'
    | '/dev/no-access'
    | '/dev/ui'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_app/'
    | '/_app/admin/bookings'
    | '/_app/admin/calendar'
    | '/_app/admin/expenses'
    | '/_app/admin/plans'
    | '/_app/admin/team'
    | '/_app/properties/$propertyId'
    | '/_app/admin/'
    | '/_app/properties/'
    | '/_app/admin/properties/$propertyId'
    | '/_app/admin/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SsoCallbackRoute: typeof SsoCallbackRoute
  DevDashboardRoute: typeof DevDashboardRoute
  DevNoAccessRoute: typeof DevNoAccessRoute
  DevUiRoute: typeof DevUiRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/dev/dashboard': {
      id: '/dev/dashboard'
      path: '/dev/dashboard'
      fullPath: '/dev/dashboard'
      preLoaderRoute: typeof DevDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/no-access': {
      id: '/dev/no-access'
      path: '/dev/no-access'
      fullPath: '/dev/no-access'
      preLoaderRoute: typeof DevNoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/dev/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/bookings': {
      id: '/_app/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AppAdminBookingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/calendar': {
      id: '/_app/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AppAdminCalendarRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/expenses': {
      id: '/_app/admin/expenses'
      path: '/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AppAdminExpensesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/plans': {
      id: '/_app/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AppAdminPlansRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/team': {
      id: '/_app/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AppAdminTeamRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/properties/': {
      id: '/_app/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AppPropertiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/properties/$propertyId': {
      id: '/_app/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof AppPropertiesPropertyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/properties/': {
      id: '/_app/admin/properties/'
      path: '/properties'
      fullPath: '/admin/properties/'
      preLoaderRoute: typeof AppAdminPropertiesIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/properties/$propertyId': {
      id: '/_app/admin/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/admin/properties/$propertyId'
      preLoaderRoute: typeof AppAdminPropertiesPropertyIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminBookingsRoute: typeof AppAdminBookingsRoute
  AppAdminCalendarRoute: typeof AppAdminCalendarRoute
  AppAdminExpensesRoute: typeof AppAdminExpensesRoute
  AppAdminPlansRoute: typeof AppAdminPlansRoute
  AppAdminTeamRoute: typeof AppAdminTeamRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminPropertiesPropertyIdRoute: typeof AppAdminPropertiesPropertyIdRoute
  AppAdminPropertiesIndexRoute: typeof AppAdminPropertiesIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminBookingsRoute: AppAdminBookingsRoute,
  AppAdminCalendarRoute: AppAdminCalendarRoute,
  AppAdminExpensesRoute: AppAdminExpensesRoute,
  AppAdminPlansRoute: AppAdminPlansRoute,
  AppAdminTeamRoute: AppAdminTeamRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminPropertiesPropertyIdRoute: AppAdminPropertiesPropertyIdRoute,
  AppAdminPropertiesIndexRoute: AppAdminPropertiesIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppPropertiesPropertyIdRoute: typeof AppPropertiesPropertyIdRoute
  AppPropertiesIndexRoute: typeof AppPropertiesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppPropertiesPropertyIdRoute: AppPropertiesPropertyIdRoute,
  AppPropertiesIndexRoute: AppPropertiesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SsoCallbackRoute: SsoCallbackRoute,
  DevDashboardRoute: DevDashboardRoute,
  DevNoAccessRoute: DevNoAccessRoute,
  DevUiRoute: DevUiRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
