/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['Health_check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['Me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['Me_update'];
    trace?: never;
  };
  '/v1/config': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['Me_config'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['Users_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['Users_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['Users_update'];
    trace?: never;
  };
  '/v1/users/{id}/deactivate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['Users_deactivate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/invites': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['Invites_list'];
    put?: never;
    post: operations['Invites_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/invites/{id}/resend': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['Invites_resend'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/invites/{id}/revoke': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['Invites_revoke'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/properties': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['Properties_list'];
    put?: never;
    post: operations['Properties_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/properties/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['Properties_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['Properties_update'];
    trace?: never;
  };
  '/v1/properties/{id}/archive': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['Properties_archive'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/properties/{id}/memberships': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['Memberships_list'];
    put?: never;
    post: operations['Memberships_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/memberships/{id}/revoke': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['Memberships_revoke'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/properties/{id}/rooms': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['Rooms_list'];
    put?: never;
    post: operations['Rooms_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/properties/{id}/rooms/order': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['Rooms_reorder'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/rooms/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['Rooms_update'];
    trace?: never;
  };
  '/v1/rooms/{id}/archive': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['Rooms_archive'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/plans': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['Plans_list'];
    put?: never;
    post: operations['Plans_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/plans/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['Plans_update'];
    trace?: never;
  };
  '/v1/plans/{id}/archive': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['Plans_archive'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/properties/{id}/plan': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['Plans_propertyPlan'];
    put?: never;
    post: operations['Plans_assign'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/bookings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['Bookings_listAll'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/properties/{id}/bookings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['Bookings_list'];
    put?: never;
    post: operations['Bookings_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/bookings/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['Bookings_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['Bookings_update'];
    trace?: never;
  };
  '/v1/bookings/{id}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['Bookings_cancel'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/audit-logs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AuditLogs_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  Health_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  Me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            phone: string | null;
            /** @enum {string|null} */
            staffRole: 'ADMIN' | null;
            /** @enum {string} */
            status: 'INVITED' | 'ACTIVE' | 'DEACTIVATED';
            memberships: {
              /** Format: uuid */
              id: string;
              /** @enum {string} */
              role: 'OWNER' | 'CLEANER';
              property: {
                /** Format: uuid */
                id: string;
                name: string;
              };
            }[];
          };
        };
      };
    };
  };
  Me_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          firstName?: string;
          lastName?: string;
          phone?: string | null;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            phone: string | null;
            /** @enum {string|null} */
            staffRole: 'ADMIN' | null;
            /** @enum {string} */
            status: 'INVITED' | 'ACTIVE' | 'DEACTIVATED';
            memberships: {
              /** Format: uuid */
              id: string;
              /** @enum {string} */
              role: 'OWNER' | 'CLEANER';
              property: {
                /** Format: uuid */
                id: string;
                name: string;
              };
            }[];
          };
        };
      };
    };
  };
  Me_config: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            taxFieldsEnabled: boolean;
          };
        };
      };
    };
  };
  Users_list: {
    parameters: {
      query?: {
        status?: 'INVITED' | 'ACTIVE' | 'DEACTIVATED';
        staffRole?: 'ADMIN';
        membershipRole?: 'OWNER' | 'CLEANER';
        cursor?: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: {
              /** Format: uuid */
              id: string;
              email: string;
              firstName: string;
              lastName: string;
              phone: string | null;
              /** @enum {string|null} */
              staffRole: 'ADMIN' | null;
              /** @enum {string} */
              status: 'INVITED' | 'ACTIVE' | 'DEACTIVATED';
              /** Format: date-time */
              createdAt: string;
            }[];
            /** Format: uuid */
            nextCursor: string | null;
          };
        };
      };
    };
  };
  Users_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            phone: string | null;
            /** @enum {string|null} */
            staffRole: 'ADMIN' | null;
            /** @enum {string} */
            status: 'INVITED' | 'ACTIVE' | 'DEACTIVATED';
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
    };
  };
  Users_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          firstName?: string;
          lastName?: string;
          phone?: string | null;
          /** @enum {string|null} */
          staffRole?: 'ADMIN' | null;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            phone: string | null;
            /** @enum {string|null} */
            staffRole: 'ADMIN' | null;
            /** @enum {string} */
            status: 'INVITED' | 'ACTIVE' | 'DEACTIVATED';
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
    };
  };
  Users_deactivate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            phone: string | null;
            /** @enum {string|null} */
            staffRole: 'ADMIN' | null;
            /** @enum {string} */
            status: 'INVITED' | 'ACTIVE' | 'DEACTIVATED';
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
    };
  };
  Invites_list: {
    parameters: {
      query?: {
        cursor?: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: {
              /** Format: uuid */
              id: string;
              /** @enum {string} */
              status: 'PENDING' | 'ACCEPTED' | 'REVOKED';
              user: {
                /** Format: uuid */
                id: string;
                email: string;
                firstName: string;
                lastName: string;
                /** @enum {string|null} */
                staffRole: 'ADMIN' | null;
              };
              emailSent: boolean;
              /** Format: date-time */
              acceptedAt: string | null;
              /** Format: date-time */
              revokedAt: string | null;
              /** Format: date-time */
              createdAt: string;
            }[];
            /** Format: uuid */
            nextCursor: string | null;
          };
        };
      };
    };
  };
  Invites_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          email: string;
          firstName: string;
          lastName: string;
          /**
           * @default null
           * @enum {string|null}
           */
          staffRole?: 'ADMIN' | null;
          /** @default [] */
          memberships?: {
            /** Format: uuid */
            propertyId: string;
            /** @enum {string} */
            role: 'OWNER' | 'CLEANER';
          }[];
        };
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: 'PENDING' | 'ACCEPTED' | 'REVOKED';
            user: {
              /** Format: uuid */
              id: string;
              email: string;
              firstName: string;
              lastName: string;
              /** @enum {string|null} */
              staffRole: 'ADMIN' | null;
            };
            emailSent: boolean;
            /** Format: date-time */
            acceptedAt: string | null;
            /** Format: date-time */
            revokedAt: string | null;
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
    };
  };
  Invites_resend: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: 'PENDING' | 'ACCEPTED' | 'REVOKED';
            user: {
              /** Format: uuid */
              id: string;
              email: string;
              firstName: string;
              lastName: string;
              /** @enum {string|null} */
              staffRole: 'ADMIN' | null;
            };
            emailSent: boolean;
            /** Format: date-time */
            acceptedAt: string | null;
            /** Format: date-time */
            revokedAt: string | null;
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
    };
  };
  Invites_revoke: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: 'PENDING' | 'ACCEPTED' | 'REVOKED';
            user: {
              /** Format: uuid */
              id: string;
              email: string;
              firstName: string;
              lastName: string;
              /** @enum {string|null} */
              staffRole: 'ADMIN' | null;
            };
            emailSent: boolean;
            /** Format: date-time */
            acceptedAt: string | null;
            /** Format: date-time */
            revokedAt: string | null;
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
    };
  };
  Properties_list: {
    parameters: {
      query?: {
        includeArchived?: 'true' | 'false';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: {
              /** Format: uuid */
              id: string;
              name: string;
              addressLine1: string;
              addressLine2: string | null;
              city: string;
              province: string;
              postalCode: string;
              country: string;
              timeZone: string;
              checkInTime: string;
              checkOutTime: string;
              provincialRegistrationNumber: string | null;
              businessLicenceNumber: string | null;
              /** Format: date-time */
              archivedAt: string | null;
              /** Format: uuid */
              defaultCleanerId?: string | null;
              defaultCleanerPayCents?: number;
              standardCleaningFeeCents?: number;
            }[];
            /** Format: uuid */
            nextCursor: string | null;
          };
        };
      };
    };
  };
  Properties_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
          addressLine1: string;
          /** @default null */
          addressLine2?: string | null;
          city: string;
          /** @default BC */
          province?: string;
          postalCode: string;
          /** @default America/Vancouver */
          timeZone?: string;
          /** @default 16:00 */
          checkInTime?: string;
          /** @default 11:00 */
          checkOutTime?: string;
          /** @default null */
          provincialRegistrationNumber?: string | null;
          /** @default null */
          businessLicenceNumber?: string | null;
          /** @default 0 */
          defaultCleanerPayCents?: number;
          /** @default 0 */
          standardCleaningFeeCents?: number;
        };
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            name: string;
            addressLine1: string;
            addressLine2: string | null;
            city: string;
            province: string;
            postalCode: string;
            country: string;
            timeZone: string;
            checkInTime: string;
            checkOutTime: string;
            provincialRegistrationNumber: string | null;
            businessLicenceNumber: string | null;
            /** Format: date-time */
            archivedAt: string | null;
            /** Format: uuid */
            defaultCleanerId?: string | null;
            defaultCleanerPayCents?: number;
            standardCleaningFeeCents?: number;
          };
        };
      };
    };
  };
  Properties_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            name: string;
            addressLine1: string;
            addressLine2: string | null;
            city: string;
            province: string;
            postalCode: string;
            country: string;
            timeZone: string;
            checkInTime: string;
            checkOutTime: string;
            provincialRegistrationNumber: string | null;
            businessLicenceNumber: string | null;
            /** Format: date-time */
            archivedAt: string | null;
            /** Format: uuid */
            defaultCleanerId?: string | null;
            defaultCleanerPayCents?: number;
            standardCleaningFeeCents?: number;
          };
        };
      };
    };
  };
  Properties_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name?: string;
          addressLine1?: string;
          addressLine2?: string | null;
          city?: string;
          province?: string;
          postalCode?: string;
          timeZone?: string;
          checkInTime?: string;
          checkOutTime?: string;
          provincialRegistrationNumber?: string | null;
          businessLicenceNumber?: string | null;
          defaultCleanerPayCents?: number;
          standardCleaningFeeCents?: number;
          /** Format: uuid */
          defaultCleanerId?: string | null;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            name: string;
            addressLine1: string;
            addressLine2: string | null;
            city: string;
            province: string;
            postalCode: string;
            country: string;
            timeZone: string;
            checkInTime: string;
            checkOutTime: string;
            provincialRegistrationNumber: string | null;
            businessLicenceNumber: string | null;
            /** Format: date-time */
            archivedAt: string | null;
            /** Format: uuid */
            defaultCleanerId?: string | null;
            defaultCleanerPayCents?: number;
            standardCleaningFeeCents?: number;
          };
        };
      };
    };
  };
  Properties_archive: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            name: string;
            addressLine1: string;
            addressLine2: string | null;
            city: string;
            province: string;
            postalCode: string;
            country: string;
            timeZone: string;
            checkInTime: string;
            checkOutTime: string;
            provincialRegistrationNumber: string | null;
            businessLicenceNumber: string | null;
            /** Format: date-time */
            archivedAt: string | null;
            /** Format: uuid */
            defaultCleanerId?: string | null;
            defaultCleanerPayCents?: number;
            standardCleaningFeeCents?: number;
          };
        };
      };
    };
  };
  Memberships_list: {
    parameters: {
      query?: {
        includeRevoked?: 'true' | 'false';
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: {
              /** Format: uuid */
              id: string;
              /** @enum {string} */
              role: 'OWNER' | 'CLEANER';
              /** Format: uuid */
              propertyId: string;
              user: {
                /** Format: uuid */
                id: string;
                email: string;
                firstName: string;
                lastName: string;
              };
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              revokedAt: string | null;
            }[];
            /** Format: uuid */
            nextCursor: string | null;
          };
        };
      };
    };
  };
  Memberships_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: uuid */
          userId: string;
          /** @enum {string} */
          role: 'OWNER' | 'CLEANER';
        };
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: 'OWNER' | 'CLEANER';
            /** Format: uuid */
            propertyId: string;
            user: {
              /** Format: uuid */
              id: string;
              email: string;
              firstName: string;
              lastName: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            revokedAt: string | null;
          };
        };
      };
    };
  };
  Memberships_revoke: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: 'OWNER' | 'CLEANER';
            /** Format: uuid */
            propertyId: string;
            user: {
              /** Format: uuid */
              id: string;
              email: string;
              firstName: string;
              lastName: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            revokedAt: string | null;
          };
        };
      };
    };
  };
  Rooms_list: {
    parameters: {
      query?: {
        includeArchived?: 'true' | 'false';
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: {
              /** Format: uuid */
              id: string;
              /** Format: uuid */
              propertyId: string;
              name: string;
              /** @enum {string} */
              type:
                'BEDROOM' | 'BATHROOM' | 'KITCHEN' | 'LIVING' | 'DINING' | 'LAUNDRY' | 'OUTDOOR' | 'ENTRY' | 'OTHER';
              sortOrder: number;
              /** Format: date-time */
              archivedAt: string | null;
            }[];
            /** Format: uuid */
            nextCursor: string | null;
          };
        };
      };
    };
  };
  Rooms_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
          /** @enum {string} */
          type: 'BEDROOM' | 'BATHROOM' | 'KITCHEN' | 'LIVING' | 'DINING' | 'LAUNDRY' | 'OUTDOOR' | 'ENTRY' | 'OTHER';
        };
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            propertyId: string;
            name: string;
            /** @enum {string} */
            type: 'BEDROOM' | 'BATHROOM' | 'KITCHEN' | 'LIVING' | 'DINING' | 'LAUNDRY' | 'OUTDOOR' | 'ENTRY' | 'OTHER';
            sortOrder: number;
            /** Format: date-time */
            archivedAt: string | null;
          };
        };
      };
    };
  };
  Rooms_reorder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          roomIds: string[];
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: {
              /** Format: uuid */
              id: string;
              /** Format: uuid */
              propertyId: string;
              name: string;
              /** @enum {string} */
              type:
                'BEDROOM' | 'BATHROOM' | 'KITCHEN' | 'LIVING' | 'DINING' | 'LAUNDRY' | 'OUTDOOR' | 'ENTRY' | 'OTHER';
              sortOrder: number;
              /** Format: date-time */
              archivedAt: string | null;
            }[];
            /** Format: uuid */
            nextCursor: string | null;
          };
        };
      };
    };
  };
  Rooms_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name?: string;
          /** @enum {string} */
          type?: 'BEDROOM' | 'BATHROOM' | 'KITCHEN' | 'LIVING' | 'DINING' | 'LAUNDRY' | 'OUTDOOR' | 'ENTRY' | 'OTHER';
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            propertyId: string;
            name: string;
            /** @enum {string} */
            type: 'BEDROOM' | 'BATHROOM' | 'KITCHEN' | 'LIVING' | 'DINING' | 'LAUNDRY' | 'OUTDOOR' | 'ENTRY' | 'OTHER';
            sortOrder: number;
            /** Format: date-time */
            archivedAt: string | null;
          };
        };
      };
    };
  };
  Rooms_archive: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            propertyId: string;
            name: string;
            /** @enum {string} */
            type: 'BEDROOM' | 'BATHROOM' | 'KITCHEN' | 'LIVING' | 'DINING' | 'LAUNDRY' | 'OUTDOOR' | 'ENTRY' | 'OTHER';
            sortOrder: number;
            /** Format: date-time */
            archivedAt: string | null;
          };
        };
      };
    };
  };
  Plans_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: {
              /** Format: uuid */
              id: string;
              name: string;
              description: string | null;
              managementFeeBps: number;
              inUse: boolean;
              /** Format: date-time */
              archivedAt: string | null;
            }[];
            /** Format: uuid */
            nextCursor: string | null;
          };
        };
      };
    };
  };
  Plans_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
          /** @default null */
          description?: string | null;
          managementFeeBps: number;
        };
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            name: string;
            description: string | null;
            managementFeeBps: number;
            inUse: boolean;
            /** Format: date-time */
            archivedAt: string | null;
          };
        };
      };
    };
  };
  Plans_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name?: string;
          description?: string | null;
          managementFeeBps?: number;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            name: string;
            description: string | null;
            managementFeeBps: number;
            inUse: boolean;
            /** Format: date-time */
            archivedAt: string | null;
          };
        };
      };
    };
  };
  Plans_archive: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            name: string;
            description: string | null;
            managementFeeBps: number;
            inUse: boolean;
            /** Format: date-time */
            archivedAt: string | null;
          };
        };
      };
    };
  };
  Plans_propertyPlan: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            current: {
              /** Format: uuid */
              id: string;
              plan: {
                /** Format: uuid */
                id: string;
                name: string;
                managementFeeBps: number;
              };
              /** Format: date */
              effectiveFrom: string;
              /** Format: date */
              effectiveTo: string | null;
            } | null;
            history: {
              /** Format: uuid */
              id: string;
              plan: {
                /** Format: uuid */
                id: string;
                name: string;
                managementFeeBps: number;
              };
              /** Format: date */
              effectiveFrom: string;
              /** Format: date */
              effectiveTo: string | null;
            }[];
          };
        };
      };
    };
  };
  Plans_assign: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: uuid */
          planId: string;
          /** Format: date */
          effectiveFrom: string;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            current: {
              /** Format: uuid */
              id: string;
              plan: {
                /** Format: uuid */
                id: string;
                name: string;
                managementFeeBps: number;
              };
              /** Format: date */
              effectiveFrom: string;
              /** Format: date */
              effectiveTo: string | null;
            } | null;
            history: {
              /** Format: uuid */
              id: string;
              plan: {
                /** Format: uuid */
                id: string;
                name: string;
                managementFeeBps: number;
              };
              /** Format: date */
              effectiveFrom: string;
              /** Format: date */
              effectiveTo: string | null;
            }[];
          };
        };
      };
    };
  };
  Bookings_listAll: {
    parameters: {
      query: {
        from: string;
        to: string;
        status?: 'CONFIRMED' | 'CANCELLED';
        kind?: 'GUEST' | 'OWNER_STAY' | 'BLOCK';
        propertyId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: {
              /** Format: uuid */
              id: string;
              /** Format: uuid */
              propertyId: string;
              /** @enum {string} */
              source: 'MANUAL' | 'ICAL' | 'PMS';
              /** @enum {string} */
              channel: 'AIRBNB' | 'VRBO' | 'BOOKING_COM' | 'DIRECT' | 'OTHER';
              /** @enum {string} */
              kind: 'GUEST' | 'OWNER_STAY' | 'BLOCK';
              /** @enum {string} */
              status: 'CONFIRMED' | 'CANCELLED';
              /** Format: date */
              checkInDate: string;
              /** Format: date */
              checkOutDate: string;
              nights: number;
              ownerGrossCents: number | null;
              complete: boolean;
              /** Format: date-time */
              cancelledAt: string | null;
              externalId?: string | null;
              checkInTimeOverride?: string | null;
              checkOutTimeOverride?: string | null;
              guestName?: string | null;
              guestCount?: number | null;
              payoutCents?: number | null;
              guestCleaningFeeCents?: number | null;
              taxesCollectedCents?: number | null;
              cancellationNote?: string | null;
              notes?: string | null;
              version?: number;
              /** Format: date-time */
              createdAt?: string;
            }[];
          };
        };
      };
    };
  };
  Bookings_list: {
    parameters: {
      query: {
        from: string;
        to: string;
        status?: 'CONFIRMED' | 'CANCELLED';
        kind?: 'GUEST' | 'OWNER_STAY' | 'BLOCK';
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: {
              /** Format: uuid */
              id: string;
              /** Format: uuid */
              propertyId: string;
              /** @enum {string} */
              source: 'MANUAL' | 'ICAL' | 'PMS';
              /** @enum {string} */
              channel: 'AIRBNB' | 'VRBO' | 'BOOKING_COM' | 'DIRECT' | 'OTHER';
              /** @enum {string} */
              kind: 'GUEST' | 'OWNER_STAY' | 'BLOCK';
              /** @enum {string} */
              status: 'CONFIRMED' | 'CANCELLED';
              /** Format: date */
              checkInDate: string;
              /** Format: date */
              checkOutDate: string;
              nights: number;
              ownerGrossCents: number | null;
              complete: boolean;
              /** Format: date-time */
              cancelledAt: string | null;
              externalId?: string | null;
              checkInTimeOverride?: string | null;
              checkOutTimeOverride?: string | null;
              guestName?: string | null;
              guestCount?: number | null;
              payoutCents?: number | null;
              guestCleaningFeeCents?: number | null;
              taxesCollectedCents?: number | null;
              cancellationNote?: string | null;
              notes?: string | null;
              version?: number;
              /** Format: date-time */
              createdAt?: string;
            }[];
          };
        };
      };
    };
  };
  Bookings_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @enum {string} */
          channel: 'AIRBNB' | 'VRBO' | 'BOOKING_COM' | 'DIRECT' | 'OTHER';
          /**
           * @default GUEST
           * @enum {string}
           */
          kind?: 'GUEST' | 'OWNER_STAY' | 'BLOCK';
          /** Format: date */
          checkInDate: string;
          /** Format: date */
          checkOutDate: string;
          /** @default null */
          externalId?: string | null;
          /** @default null */
          checkInTimeOverride?: string | null;
          /** @default null */
          checkOutTimeOverride?: string | null;
          /** @default null */
          guestName?: string | null;
          /** @default null */
          guestCount?: number | null;
          /** @default null */
          payoutCents?: number | null;
          /** @default null */
          guestCleaningFeeCents?: number | null;
          /** @default null */
          taxesCollectedCents?: number | null;
          /** @default null */
          notes?: string | null;
        };
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            propertyId: string;
            /** @enum {string} */
            source: 'MANUAL' | 'ICAL' | 'PMS';
            /** @enum {string} */
            channel: 'AIRBNB' | 'VRBO' | 'BOOKING_COM' | 'DIRECT' | 'OTHER';
            /** @enum {string} */
            kind: 'GUEST' | 'OWNER_STAY' | 'BLOCK';
            /** @enum {string} */
            status: 'CONFIRMED' | 'CANCELLED';
            /** Format: date */
            checkInDate: string;
            /** Format: date */
            checkOutDate: string;
            nights: number;
            ownerGrossCents: number | null;
            complete: boolean;
            /** Format: date-time */
            cancelledAt: string | null;
            externalId?: string | null;
            checkInTimeOverride?: string | null;
            checkOutTimeOverride?: string | null;
            guestName?: string | null;
            guestCount?: number | null;
            payoutCents?: number | null;
            guestCleaningFeeCents?: number | null;
            taxesCollectedCents?: number | null;
            cancellationNote?: string | null;
            notes?: string | null;
            version?: number;
            /** Format: date-time */
            createdAt?: string;
          };
        };
      };
    };
  };
  Bookings_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            propertyId: string;
            /** @enum {string} */
            source: 'MANUAL' | 'ICAL' | 'PMS';
            /** @enum {string} */
            channel: 'AIRBNB' | 'VRBO' | 'BOOKING_COM' | 'DIRECT' | 'OTHER';
            /** @enum {string} */
            kind: 'GUEST' | 'OWNER_STAY' | 'BLOCK';
            /** @enum {string} */
            status: 'CONFIRMED' | 'CANCELLED';
            /** Format: date */
            checkInDate: string;
            /** Format: date */
            checkOutDate: string;
            nights: number;
            ownerGrossCents: number | null;
            complete: boolean;
            /** Format: date-time */
            cancelledAt: string | null;
            externalId?: string | null;
            checkInTimeOverride?: string | null;
            checkOutTimeOverride?: string | null;
            guestName?: string | null;
            guestCount?: number | null;
            payoutCents?: number | null;
            guestCleaningFeeCents?: number | null;
            taxesCollectedCents?: number | null;
            cancellationNote?: string | null;
            notes?: string | null;
            version?: number;
            /** Format: date-time */
            createdAt?: string;
          };
        };
      };
    };
  };
  Bookings_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @enum {string} */
          channel?: 'AIRBNB' | 'VRBO' | 'BOOKING_COM' | 'DIRECT' | 'OTHER';
          /** @enum {string} */
          kind?: 'GUEST' | 'OWNER_STAY' | 'BLOCK';
          /** Format: date */
          checkInDate?: string;
          /** Format: date */
          checkOutDate?: string;
          externalId?: string | null;
          checkInTimeOverride?: string | null;
          checkOutTimeOverride?: string | null;
          guestName?: string | null;
          guestCount?: number | null;
          payoutCents?: number | null;
          guestCleaningFeeCents?: number | null;
          taxesCollectedCents?: number | null;
          notes?: string | null;
          version: number;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            propertyId: string;
            /** @enum {string} */
            source: 'MANUAL' | 'ICAL' | 'PMS';
            /** @enum {string} */
            channel: 'AIRBNB' | 'VRBO' | 'BOOKING_COM' | 'DIRECT' | 'OTHER';
            /** @enum {string} */
            kind: 'GUEST' | 'OWNER_STAY' | 'BLOCK';
            /** @enum {string} */
            status: 'CONFIRMED' | 'CANCELLED';
            /** Format: date */
            checkInDate: string;
            /** Format: date */
            checkOutDate: string;
            nights: number;
            ownerGrossCents: number | null;
            complete: boolean;
            /** Format: date-time */
            cancelledAt: string | null;
            externalId?: string | null;
            checkInTimeOverride?: string | null;
            checkOutTimeOverride?: string | null;
            guestName?: string | null;
            guestCount?: number | null;
            payoutCents?: number | null;
            guestCleaningFeeCents?: number | null;
            taxesCollectedCents?: number | null;
            cancellationNote?: string | null;
            notes?: string | null;
            version?: number;
            /** Format: date-time */
            createdAt?: string;
          };
        };
      };
    };
  };
  Bookings_cancel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          version: number;
          /** @default null */
          note?: string | null;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            propertyId: string;
            /** @enum {string} */
            source: 'MANUAL' | 'ICAL' | 'PMS';
            /** @enum {string} */
            channel: 'AIRBNB' | 'VRBO' | 'BOOKING_COM' | 'DIRECT' | 'OTHER';
            /** @enum {string} */
            kind: 'GUEST' | 'OWNER_STAY' | 'BLOCK';
            /** @enum {string} */
            status: 'CONFIRMED' | 'CANCELLED';
            /** Format: date */
            checkInDate: string;
            /** Format: date */
            checkOutDate: string;
            nights: number;
            ownerGrossCents: number | null;
            complete: boolean;
            /** Format: date-time */
            cancelledAt: string | null;
            externalId?: string | null;
            checkInTimeOverride?: string | null;
            checkOutTimeOverride?: string | null;
            guestName?: string | null;
            guestCount?: number | null;
            payoutCents?: number | null;
            guestCleaningFeeCents?: number | null;
            taxesCollectedCents?: number | null;
            cancellationNote?: string | null;
            notes?: string | null;
            version?: number;
            /** Format: date-time */
            createdAt?: string;
          };
        };
      };
    };
  };
  AuditLogs_list: {
    parameters: {
      query?: {
        entityType?: string;
        entityId?: string;
        propertyId?: string;
        actorId?: string;
        cursor?: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: {
              /** Format: uuid */
              id: string;
              /** @enum {string} */
              actorType: 'USER' | 'SYSTEM';
              /** Format: uuid */
              actorId: string | null;
              action: string;
              entityType: string;
              /** Format: uuid */
              entityId: string;
              /** Format: uuid */
              propertyId: string | null;
              before: unknown;
              after: unknown;
              /** Format: date-time */
              createdAt: string;
            }[];
            /** Format: uuid */
            nextCursor: string | null;
          };
        };
      };
    };
  };
}
